inputs_def:
  - handle: df
    description: Input
    json_schema:
      contentMediaType: oomol/var
  - handle: stock_name
    json_schema:
      type: string
outputs_def:
  - handle: df
    description: Output
    json_schema:
      contentMediaType: oomol/var
icon: ":fa6-solid:computer:currentColor:"
ui:
  default_width: 530
executor:
  name: python
  options:
    spawn: false
    entry: main.py
